7040883: Compilation error: "length in Array is defined in an inaccessible class or interface"
Fix of 7034511 (now backed out) is causing spurious accessibility errors

Reviewed-by: jjg